# Spring SQL Initialization
spring:
    sql:
        init:
            mode: always

# --- Database 1 (Primary) ---
db1:
    jdbc-url: jdbc:firebird://localhost:3050/D:/javaDemo1/TESTHIBERNET.FDB?encoding=UTF8
    driver-class-name: org.firebirdsql.jdbc.FBDriver
    username: SYSDBA
    password: masterkey
    maximum-pool-size: 3
    minimum-idle: 2
    connection-timeout: 30000
    auto-commit: true
    pool-name: db1-pool

# --- Database 2 (Secondary) ---
db2:
    jdbc-url: jdbc:firebird://localhost:3050/D:/javaDemo1/TESTHIBERNET.FDB?encoding=UTF8
    driver-class-name: org.firebirdsql.jdbc.FBDriver
    username: SYSDBA
    password: masterkey
    maximum-pool-size: 4
    minimum-idle: 2
    connection-timeout: 30000
    auto-commit: true
    pool-name: db2-pool
    
logging:
    level:
        org:
            springframework:
                jdbc:
                    core:
                        JdbcTemplate: DEBUG
                        



                        