# Spring SQL Initialization
spring:
    sql:
        init:
            mode: always

logging:
    level:
        org:
            springframework:
                jdbc:
                    core:
                        JdbcTemplate: DEBUG
                        
# --- Database 1 (Primary) ---
db1:
    jdbc-url: jdbc:firebird://localhost:3050/D:/javaDemo1/TESTHIBERNET.FDB?encoding=UTF8
    driver-class-name: org.firebirdsql.jdbc.FBDriver
    username: SYSDBA
    password: masterkey
    hikari.maximum-pool-size: 3
    hikari.minimum-idle: 2
    hikari.connection-timeout: 30000
    hikari.auto-commit: true

# --- Database 2 (Secondary) ---
db2:
    jdbc-url: jdbc:firebird://localhost:3050/D:/javaDemo1/TESTHIBERNET.FDB?encoding=UTF8
    driver-class-name: org.firebirdsql.jdbc.FBDriver
    username: SYSDBA
    password: masterkey
    hikari.maximum-pool-size: 3
    hikari.minimum-idle: 2
    hikari.connection-timeout: 30000
    hikari.auto-commit: true


                        