
# --- Database 1 (Primary) ---
spring.datasource.db1.jdbc-url=jdbc:firebird://localhost:3050/D:/javaDemo1/TESTHIBERNET.FDB?encoding=UTF8
spring.datasource.db1.driver-class-name=org.firebirdsql.jdbc.FBDriver
spring.datasource.db1.username=SYSDBA
spring.datasource.db1.password=masterkey
spring.datasource.db1.hikari.maximum-pool-size=3
spring.datasource.db1.hikari.minimum-idle=2
spring.datasource.db1.hikari.connection-timeout=30000
spring.datasource.db1.hikari.auto-commit=true

# --- Database 2 (Secondary) ---
spring.datasource.db2.jdbc-url=jdbc:firebird://localhost:3050/D:/javaDemo1/TESTHIBERNET.FDB?encoding=UTF8
spring.datasource.db2.driver-class-name=org.firebirdsql.jdbc.FBDriver
spring.datasource.db2.username=SYSDBA
spring.datasource.db2.password=masterkey
spring.datasource.db2.hikari.maximum-pool-size=3
spring.datasource.db2.hikari.minimum-idle=2
spring.datasource.db2.hikari.connection-timeout=30000
spring.datasource.db2.hikari.auto-commit=true

# Spring SQL Initialization
spring.sql.init.mode=always

logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG